# Generated by Django 3.1.6 on 2021-02-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_DXC',
            field=models.BooleanField(default=True),
        ),
    ]
